Repository lncm/pi-factory, pull requests merged in 2019-04, with the labels that each got.

#163 [TO TEST] [To: 3.9.0] Add new invoicer config
  home/lncm/invoicer/invoicer.conf
Labels: enhancement

#204 Add Vagrantfile for running make-img.sh
  Vagrantfile
  make_img.sh
Labels: enhancement

#208 Update LND, remove bridged network
  home/lncm/compose/clearnet/docker-compose.yml
  home/lncm/compose/tor/docker-compose.yml
Labels: enhancement

#206 Vagrant complete
  README.md
  Vagrantfile
  docs/README.md
  make_img.sh
Labels: bug, enhancement

#193 Fix up nginx.conf so that both POS and WIFI is working
  etc/nginx/conf.d/default.conf
Labels: bug

#201 Enable tor + clearnet hybrid; document settings
  home/lncm/bitcoin/bitcoin.conf
Labels: enhancement

#210 Make error message more meaningful (/etc/init.d/docker-compose)
  etc/init.d/docker-compose
Labels: enhancement
